### ISSUE TITLE
Shawn - Plan character design

### ISSUE THREAD

**Issue by shawwill2** [Gyle/parrychris_OneHit_P2#13]

**Comment by xlShawn** [comment]
![fighter](https://user-images.githubusercontent.com/32561911/46112995-c5fa2280-c240-11e8-931e-f6d6450260c5.jpg)

**Comment by xlShawn** [comment]
![samurai](https://user-images.githubusercontent.com/32561911/46113044-f477fd80-c240-11e8-916d-d75dd6fa0936.jpg)

**Comment by xlShawn** [comment]
![munk_kunfu](https://user-images.githubusercontent.com/32561911/46113384-3e151800-c242-11e8-91f0-24e9917ef772.jpg)
