### ISSUE TITLE
@milnejaim - Feedback on One Hit

### ISSUE THREAD

**Issue by Gyle** [Gyle/parrychris_OneHit_P2#29]
Levels feel too small lengthwise. There's not quite enough room to move around satisfactorily. The dash feels too long, because you can travel most of the width of the level using it only once. The player character can jump very high, but not very far, which feels quite strange when playing -- could be fixed by adding the ability to dash in mid-air? Mechanics are very fun regardless. I loved the ground pound/stomp move, although it was very difficult to execute.

**Comment by tomBeep** [comment]
I think this is excellent feedback from Jaime with some very good points. The improvements we plan to make from this feedback are:
A) Increase the width of the levels. This is already partially complete as our upcoming new map is much wider horizontally.
B) Add mid-air dashing. This is very important as it allows much more strategical movement while in the air. 

Response by Thomas Edwards (edwardthom)
