### ISSUE TITLE
Character Select Screen

### ISSUE THREAD

**Issue by Gyle** [Gyle/parrychris_OneHit_P2#53]
Players pick their characters and displays idle animation of characters they're hovering over

**Comment by Gyle** [comment]
To help with this issue, I will extend my implementation for character select by adding a Sprite Manager class. This class will help with changing the character sprites and any other image sprites for modularity.

**Comment by Gyle** [comment]
design so far
![screen shot 2018-10-31 at 7 29 37 pm](https://user-images.githubusercontent.com/18452019/47770213-67462e00-dd43-11e8-9662-37ef17e225fb.png)

**Comment by Gyle** [comment]
All the functionality is there, including carrying data over through scenes. What is left is to finalise the design of the character select scene. Once this has happened, we can safely close this issue

**Comment by ZiggyNZ** [comment]
Now works with the data storer and characters can now be selected
